### ISSUE TITLE
Multiple WebComponents on Same page

### ISSUE THREAD

**Issue by pedrodgfaria** [Silind-Software/direflow#12] opened 2019-11-26 14:41 UTC
Hi,

When consuming the bundle, having multiple components on same page, a setState invocked in one, provoque the same result on the others, i'm missing something?

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="public/index.css">
    <title>Direflow Test</title>

    <script src="componentBundle.js"></script>
</head>
<body>
<component style="width:400px"></component>
<component style="width:400px"></component>
</body>
</html>

```

so if i have a state change on a "onClick" action, it will be interpreted by the 2 components.

**Comment by Silind** [comment] 2019-11-26 15:05
Hi @pedrodgfaria 

Thank you for creating this issue :+1: 

That is definitely unintended behavior.
I will look into this as soon as possible.

**Comment by pedrodgfaria** [comment] 2019-11-27 09:12
The problem was in my implementation not in the project, sorry for the time lost

**Comment by pedrodgfaria** [comment] 2019-11-27 09:21
the call of setState in one doesn't trigger immediatly on the other one, but when the other re-renders he get the same state from the first one

**Comment by pedrodgfaria** [comment] 2019-11-27 10:00
problem was i was using the same reference to all the components:

`
export const componentProperties = {
 someProp: new Set()
}
`

this causes same reference on all usages so the "same state" (not really) on rending the prop.


Sorry for time lost

**Comment by Silind** [comment] 2019-11-27 10:02
Ahh, I see.
No worries, thanks for discovering and closing the issue :+1:

**Comment by pedrodgfaria** [comment] 2019-12-02 16:12
Is a tricky one, but is realy sharing props,

[example](https://drive.google.com/file/d/1RzPivz_zeQVf_7SU7XMpF5XUap_2vSky/view)


componentProperties.js

```
/**
 * Update proptypes to reflect the types of the properties and attributes
 */
export const propTypes = {
    todos: PropTypes.array,
    componentTitle: PropTypes.string,
    testProp: PropTypes.string,
};

/**
 * Update this object with the initial values of the properties
 */
export const componentProperties = {
    todos: [
        'Go to src/componentProperties.ts...',
        'Register properties and attributes...',
        'Build awesome React Web Component!',
    ],
    componentTitle: 'Test Component',
    testProp: 'Test Component',
};

/**
 * Update this object with the initial values of the attributes
 */
export const componentAttributes = {};
```

app.js

```
const App = (props) => {
  const dispatch = useContext(EventContext);

  const handleClick = () => {
    const event = new Event('my-event');
    dispatch(event);
  };

  const renderTodos = props.todos.map((todo) => (
    <li key={todo} className='todo-title'>
      {todo}
    </li>
  ));

  return (
    <Styled styles={styles}>
      <div className='app'>
        <div className='header-title'>{props.componentTitle}</div>
        <div className='sub-title'>{props.testProp}</div>
        <div className='todo-list'>
          <ul>{renderTodos}</ul>
        </div>
        <button className='button' onClick={handleClick}>
          Let's go!
        </button>
      </div>
    </Styled>
  );
};

App.propTypes = propTypes;

export default App;
```

using:
```
const handleTest = (component) => {
    console.log(component);

    function makeid(length) {
        var result = '';
        var characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
        var charactersLength = characters.length;
        for (var i = 0; i < length; i++) {
            result += characters.charAt(Math.floor(Math.random() * charactersLength));
        }
        return result;
    }

    component.componentTitle = makeid(5);
    component.testProp = makeid(5);

    setTimeout(function() {
        component.testProp = 'only this should change'
    }, 3000)
};
```

As u can see the first component is getting the title from the second component after setting another prop.

**Comment by Silind** [comment] 2019-12-02 20:45
Yeah, I see something odd going on there.
Thank you for thorough reproduction steps.
I will look into this issue asap.

**Comment by pedrodgfaria** [comment] 2019-12-03 10:17
Hi, these changes in CustomComponent.tsx make me think they do the trick. Maybe this will help you.

```
class CustomComponent extends HTMLElement {
  private _application: JSX.Element | undefined;
  private properties: any = Object.assign({}, componentProperties);
```

```
  private reactProps(): any {
    const attributes = {} as any;

    Object.keys(componentAttributes).forEach((key: string) => {
      attributes[key] = this.getAttribute(key) || (componentAttributes as any)[key];
    });

    return {...attributes, ...this.properties};
  }

```

```
 public reactPropsChangedCallback(name: string, oldValue: any, newValue: any): void {
    if (oldValue === newValue) {
      return;
    }

    this.properties[name] = newValue;

    this.mountReactApp();
  }
```

**Comment by Silind** [comment] 2019-12-03 10:26
Awesome, thanks! :smile: 
You are also more than welcome to do a PR on this, if you can verify that it solves the problem.
Then I'll review as soon as I get time :+1:

**Comment by pedrodgfaria** [comment] 2019-12-03 10:48
This solves the reference of shared props, but this one also needs a workaround:

`    Object.defineProperties(CustomComponent.prototype, propertyMap);
`

some prop's ( e.g. boolean props) are not triggering all time, need to set 2 times to get the expected behaviour, can this be done without setting in prototype?

**Comment by pedrodgfaria** [comment] 2019-12-03 11:00
```
class CustomComponent extends HTMLElement {
  private _application: JSX.Element | undefined;
  private properties: any = Object.assign({}, componentProperties);

  constructor() {
    super();
    const propertyMap = {} as PropertyDescriptorMap;
    Object.keys(this.properties).forEach((key: string) => {
      propertyMap[key] = {
        configurable: true,
        enumerable: true,
        get(): any {
          return (this as any).properties[key];
        },
        set(newValue: any): any {
          const oldValue = (this as any).properties[key];
          (this as any).properties[key] = newValue;
          (this as any).reactPropsChangedCallback(key, oldValue, newValue);
        },
      };
    });

    Object.defineProperties(CustomComponent.prototype, propertyMap);
  }
```

Removing the snippet from DireflowComponent.tsx and moving to CustomComponent.tsx to make them access the private field resolved my issue, but i think it's better you have a look when you get time

**Comment by Silind** [comment] 2019-12-03 11:03
I will - thank you for all the snippets :slightly_smiling_face:

**Comment by pedrodgfaria** [comment] 2019-12-03 20:11
I created a pull request to help you.

**Comment by Silind** [comment] 2019-12-04 06:46
Awesome, @pedrodgfaria! Thank you :pray: 
I'll review the changes as soon as possible :smile:

**Closed** 2019-12-10 16:25 UTC
Labels: Direflow Component, help wanted
