### ISSUE TITLE
Build failed with TypeScript direflow project

### ISSUE THREAD

**Issue by somsharp** [Silind-Software/direflow#19] opened 2019-12-09 23:07 UTC
Here are steps to repro the same:

Step 1: direflow create -p (choose TypeScript as project)
Step 2: direflow create (after change current directory and created cool component TypeScript type)
Step 3: yarn install
Step 4: yarn build (build failed with below error)

Error Message: 
yarn run v1.19.1
$ direflow-project build

Please be patient
Building all Direflow Components...

Build started: cool-component
Build success: cool-component

Creating production build ...

events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn webpack ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by Silind** [comment] 2019-12-10 16:05
Hi @somsharp 
Thank you for creating this issue.
I've been able to reproduce the problem from your steps and found that this occurs when you try to build a project with no Direflow Components in it.
If you create at least 1 Direflow Component, the build succeeds.

This is, of course, something that should be fixed - thank you for bringing this to my attention :+1:

**Comment by somsharp** [comment] 2019-12-10 19:26
Please have a look at the below folder structure. The Direflow component named 'cool-component' is already present. One thing I have noticed that from the component directory I am able to run and build the component but when I am trying to build it from project level it is failing. There is something definitely going wrong in the project level build. Can you give a sample project with a basic component so that I can download it and give a try whether it works for me or not? 
--ccm
----direflow-components
------cool-component
--------build
--------node_modules
--------public
--------src
--------.env
--------direflow-config.js
--------direflow-webpack.js
--------package.json
--------README.md
--------tsconfig.json
--------tslint.json
--------yarn.lock
----node_modules
----public
----src
----direflow-config.js
----direflow-webpack.js
----package.json
----README.md
----tsconfig.json
----tslint.json
----yarn.lock

**Comment by pedrodgfaria** [comment] 2019-12-10 19:37
Hi, are you using windows system?

**Comment by somsharp** [comment] 2019-12-10 19:39
Yes. 64-bit Windows 10 Enterprise Operating System

**Comment by pedrodgfaria** [comment] 2019-12-10 20:01
you can run the webpack command to get the build as a workaround

[source reference](https://github.com/Silind-Software/direflow/blob/38eba7c84653b6309e89b3f4954e3dcb39d6b6a8/packages/direflow-project/tasks/tasks.sh)


`node ./node_modules/webpack/bin/webpack.js --config ./node_modules/direflow-project/config/config.production.js`


The problem is that child_process can't run webpack

```
Error: spawn webpack ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn webpack',
  path: 'webpack',
  spawnargs: [
    '--config',
    './node_modules/direflow-project/config/config.production.js'
  ]
}



```

**Comment by somsharp** [comment] 2019-12-10 20:09
Thanks. webpack command worked for me. I am waiting for the feature "Ability to create multiple components from the same setup." which will help me a lot as we have more than 50 existing component to expose via web-component. Let me know when we can use it?

**Comment by Silind** [comment] 2019-12-10 21:17
Ahh, I see. Can I ask, which version of `direflow-project` are you using in your project setup?
From `direflow-project` 1.0.20 and above the child_process was replaced with shell scripts.
Could you try to upgrade to the latest version?

Thanks a lot for the help, @pedrodgfaria :blush: 
Nice that you spotted the issue already.

@somsharp, I expect that we'll have release 2.0.0 ready during this week and available from next week.
However, in the very latest version of `direflow-component`, you are now allowed to do the following in your `index.js` / `index.tsx` file:
```javascript
const direflowComponent = new DireflowComponent();

direflowComponent.setAttributes(attributes);
direflowComponent.setProperties(properties);
direflowComponent.render(App, 'some-component');

const anotherComponent = new DireflowComponent();

anotherComponent.setAttributes(attributes);
anotherComponent.setProperties(properties);
anotherComponent.render(Another, 'another-component');
```
This gives you the ability to expose multiple React Components as different Web Components from the same build setup, without using the 'Direflow Project' feature.
In version 2.0.0 other related features will be included, but this should get you started already :slightly_smiling_face:

**Comment by somsharp** [comment] 2019-12-10 21:28
@Silind you are right. I am using "direflow-project": "1.0.19" here. Glad to know that 2.0 is coming soon. Thanks for making it possible to allow multiple web-component in a single Direflow Component. Awesome contribution.

**Closed** 2019-12-11 07:08 UTC
Labels: Direflow Project, bug

**Comment by mgm87** [comment] 2020-03-18 20:52
Why is this closed? I have the same issue in v3.4.4
It looks like the discussion changed topics halfway through and was closed without resolving the issue...

**Comment by Silind** [comment] 2020-03-19 06:37
Hi @mgm87 
This issue is closed because it's about using `direflow-project` which was deprecated in v2.

Kindly create a new issue and describe your problem 🙂

**Comment by albert-dm** [comment] 2021-04-13 11:58
I'm getting this with v3... 

alber@DESKTOP-BLHLT91 MINGW64 ~/Documents/work/ambaya/code/ambaya-v2/ambaya-design (main)
$ yarn build:lib
yarn run v1.22.4
$ direflow-scripts build:lib
Building React component library...
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn webpack ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn webpack',
  path: 'webpack',
  spawnargs: [
    '--config',
    'C:\\Users\\alber\\Documents\\work\\ambaya\\code\\ambaya-v2\\ambaya-design\\node_modules\\direflow-scripts\\webpack.config.js'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by luchobertello** [comment] 2021-05-05 15:13
Same issue here. Direflow v3.5.5
Windows 10 Enterprise 64bit
