### ISSUE TITLE
build create a bundle that not work

### ISSUE THREAD

**Issue by seeiuu** [Silind-Software/direflow#92] opened 2020-03-04 19:36 UTC
I have try to use 

`"direflow-component": "3.3.1"`

simple following your documentations.
All work like a charm, until I try to build the application

`npm run build`

It create a "direflowBundle.js" of only 4KB... I have put in my index.html and run a server... but it only added this two row

`<script async="" src="https://unpkg.com/react-dom@16/umd/react-dom.production.min.js"></script><script async="" src="https://unpkg.com/react@16/umd/react.production.min.js"></script></head>
`
but my tag not keep live

I received only in browser console this message

`direflowBundle.js:1 No index-file was found. Did you move the index-file from src?`

have you some idea?

thanks in advantace

**Comment by Silind** [comment] 2020-03-04 20:58
Hi @seeiuu 
Thank you for creating this issue.

I cannot reproduce the problem you're describing. Would you kindly elaborate on the following:
1. There should be an index.js or index.tsx file inside your `src` folder of the project. Did you remove or rename that file?
2. Are you using TypeScript or JavaScript for your setup?
3. Which package manager did you use to install? Yarn or NPM?
4. Which OS are you running on?

We'll have a look when we know a little more  :slightly_smiling_face:

**Comment by seeiuu** [comment] 2020-03-04 22:28
Thanks @Silind for reply!!!

I have do this step. I am with a Windows 10 64bit, the last update (more o less... I think)

I simple make this step:

1) npx direflow-cli create (I don't like install globally the cli stuff) and follow the wizard
2) npm run build 
3) I try with js and ts

Perhaps the problem is with "npx"?

Thanks again!!!

**Comment by Silind** [comment] 2020-03-05 07:41
Hi @seeiuu 
Using npx should be perfectly fine - it shouldn't make a difference.

I just checked with npx, with both yarn and npm, both TypeScript and JavaScript, and on a Linux (Ubuntu) and a Mac, and I still cannot reproduce the problem.

I suspect that this is a Windows related issue.
We will investigate further 👍 

Last question though.
Did you name your component something starting with a 'u'?
We just received another [issue](https://github.com/Silind-Software/direflow/issues/91) regarding issues on Windows.

**Comment by seeiuu** [comment] 2020-03-05 08:07
Hi @Silind this morning I have try again, 
this is the step that I did:

1. `npx direflow-cli create`
1.  on question for name I chose "myelement"
1. `npm install `
1. `npm run build`
1. I went to the "build" dir, and copy the index.html that I found in "public" dir
1. I have add to this file <script src="./direflowBundle.js"></script> in the head section
1. I have run in build dir `npx http-server`

After this, I have open the browser and the only things that appen is what I have mentionate in first my comment.

I hope that help you

**Comment by JohnDeved** [comment] 2020-03-05 11:53
I just successfully recreated the issue on a windows machine.

npm start works
npm run build creates the error message as described

**Comment by Silind** [comment] 2020-03-05 14:12
Alright, so we narrowed this problem down.
We will look into this as soon as possible 👍 

Until then, try to use version 3.2.8.
It comes with a larger bundle size, but it should build properly.

**Comment by BastianMa** [comment] 2020-03-16 12:01
Windows 10, direflow 3.4.3 (cli and project):
new Project - npm run start and npm run build doesn't work

**Comment by Silind** [comment] 2020-03-17 07:51
Hi @BastianMa 
From version 3.4, all Direflow Components must be located in a folder `src/direflow-components`.
Check [this article](https://medium.com/@simonlhoiberg/direflow-v3-4-0-release-notes-60e1caff3805) to get an overview over breaking changes in 3.4.

There could be a more descriptive error message, though.
We will include that in the next patch 👍

**Comment by BastianMa** [comment] 2020-03-17 08:01
The structure is there, its a new generated project. 🤔

**Comment by Silind** [comment] 2020-03-17 09:45
Oh, I see.
I assume this is yet again path related on Windows OS.
We will look into this as soon as possible.

Thanks for creating this issue.

**Comment by daffyl0s** [comment] 2020-03-23 10:29
I am having the same issue using Windows 10.
Cannot Start/Build with error: ENOENT: no such file or directory, scandir '/direflow-components'
Any updates?

**Comment by Silind** [comment] 2020-03-23 11:11
Hi @daffyl0s, @BastianMa and @seeiuu 
We expect to roll out a patch version that includes a fix for this within the next couple of days :slightly_smiling_face:

**Closed** 2020-03-24 15:02 UTC
Labels: Bug

**Comment by seeiuu** [comment] 2020-03-24 15:37
Well done! Thanks!
